# Generated by Django 3.0.5 on 2025-11-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attentionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Por atender'), ('approved', 'Aprobada'), ('done', 'Atendida')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiólogo', 'Cardiólogo'), ('Dermatólogo', 'Dermatólogo'), ('Especialista en Medicina de Emergencias', 'Especialista en Medicina de Emergencias'), ('Alergólogo/Inmunólogo', 'Alergólogo/Inmunólogo'), ('Anestesiólogo', 'Anestesiólogo'), ('Cirujano Colorrectal', 'Cirujano Colorrectal')], default='Cardiologist', max_length=50),
        ),
    ]
