# Generated by Django 3.0.5 on 2025-11-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20251122_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='attentionDate',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
