# Generated by Django 3.0.5 on 2025-11-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20251122_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'En espera'), ('done', 'Atendido'), ('cancelled', 'Cancelado')], default='pending', max_length=10),
        ),
    ]
