# Generated by Django 3.0.5 on 2025-11-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_appointment_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='payment_status',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Total'),
        ),
    ]
